Create xSerendipity
hakusaro/facts pull request #61
Opened 2017-10-31 06:24 UTC by xSerendipity

2017-10-31 23:38 UTC, hakusaro requested changes
Cannot merge until your submission has the ```.md``` file extension.

2017-11-02 17:35 UTC, xSerendipity reviewed
Hopefully this is correct - I am new to github. Please let me know if there is something different I should do.

2017-11-02 18:42 UTC, hakusaro commented
That's all good! Thank you very much!

![lgtm](https://user-images.githubusercontent.com/532647/32344083-3d05a63e-bfcb-11e7-96d9-a9ad5a32f668.gif)

2017-11-02 18:42 UTC, hakusaro approved these changes

2017-11-02 18:42 UTC, merged